version: '3.8'

services:
    db:
        image: mysql:8.0
        container_name: booking_system_db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: organization_directory
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        volumes:
            - dbdata:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - laravel
        command: --default-authentication-plugin=mysql_native_password

networks:
    laravel:
        driver: bridge

volumes:
    dbdata:
        driver: local
